kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-config
  namespace: plex
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-transcode
  namespace: plex
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
