apiVersion: v1
kind: Namespace
metadata:
  name: plex
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: plex-data
  name: plex-data
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  flexVolume:
    driver: ceph.rook.io/rook
    fsType: ceph
    options:
      clusterNamespace: rook-ceph
      fsName: ceph-filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: rook-cephfs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-data
  namespace: plex
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: plex-data
  resources:
    requests:
      storage: 50Gi
