apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: rook-ceph
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - port: 80
    name: web
    targetPort: web
    protocol: TCP
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-storage
  namespace: rook-ceph
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: rook-ceph
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - name: web
          containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
        env:
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "hello"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-kubernetes-app"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-storage
